name: Upload

on:
  push:
    tags:
      - 0.*

jobs:
  build-linux:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install conan
      run: pip install conan==1.59
      
    - name: Build and test conan package
      run: conan create . admin/stable

    - name: Add remote artifactory
      run: conan remote add otus http://otus-artifactory-cpp-ce.filonovpv.name/artifactory/api/conan/conan

    - name: Upload conan package
      run: conan user -p ${{secrets.CONAN_PASSWORD}} ${{ secrets.CONAN_USERNAME }} -r otus &&
           conan upload --confirm hello/0.*@admin/stable --all -r otus

  build-windows:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Install conan
      run: pip install conan==1.59
      
    - name: Build and test conan package
      run: conan create . admin/stable

    - name: Add remote artifactory
      run: conan remote add otus http://otus-artifactory-cpp-ce.filonovpv.name/artifactory/api/conan/conan

    - name: Upload conan package
      run: conan user -p ${{secrets.CONAN_PASSWORD}} ${{ secrets.CONAN_USERNAME }} -r otus &&
           conan upload --confirm hello/0.*@admin/stable --all -r otus

  build-macosx:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Install conan
      run: pip install conan==1.59
      
    - name: Build and test conan package
      run: conan create . admin/stable

    - name: Add remote artifactory
      run: conan remote add otus http://otus-artifactory-cpp-ce.filonovpv.name/artifactory/api/conan/conan

    - name: Upload conan package
      run: conan user -p ${{secrets.CONAN_PASSWORD}} ${{ secrets.CONAN_USERNAME }} -r otus &&
           conan upload --confirm hello/0.*@admin/stable --all -r otus

